version: 0.0.{build}

skip_non_tags: false

image: Visual Studio 2017

configuration: Release

shallow_clone: true

environment:
  NUGET_FLAGS: "-Verbosity quiet -Prop Configuration=Release -OutputDirectory dist"

# Install MonoGame 3.6
init:
- ps: >-
    (New-Object Net.WebClient).DownloadFile('http://www.monogame.net/releases/v3.6/MonoGameSetup.exe', 'C:\MonoGameSetup.exe')

    Invoke-Command -ScriptBlock {C:\MonoGameSetup.exe /S /v/qn}

before_build:
- cmd: nuget restore -Verbosity quiet

# Build NuGet packages
after_build:
- cmd: >-
    if %APPVEYOR_REPO_TAG% neq false (set NUGET_FLAGS="%NUGET_FLAGS% -Version '%APPVEYOR_REPO_TAG%'") else (set NUGET_FLAGS="%NUGET_FLAGS% -Version '%APPVEYOR_BUILD_VERSION%'")

    nuget pack %NUGET_FLAGS% ./Nez.Portable/Nez.nuspec

    nuget pack %NUGET_FLAGS% ./Nez.FarseerPhysics/Nez.FarseerPhysics.nuspec

    nuget pack %NUGET_FLAGS% ./Nez.PipelineImporter/Nez.PipelineImporter.nuspec

artifacts:
- path: dist\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  on:
    appveyor_repo_tag: true
  api_key:
  secure: "ENCRYPTED API KEY HERE"